// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/_middleware.ts";
import * as $4 from "./routes/about.tsx";
import * as $5 from "./routes/accreditation.tsx";
import * as $6 from "./routes/akvaplanist.tsx";
import * as $7 from "./routes/api/mynewsdesk/index.ts";
import * as $8 from "./routes/api/mynewsdesk/type/[...path].ts";
import * as $9 from "./routes/api/mynewsdesk/year/[...path].ts";
import * as $10 from "./routes/api/projects.ts";
import * as $11 from "./routes/api/slug/[type].ts";
import * as $12 from "./routes/article/[slug].tsx";
import * as $13 from "./routes/careers.tsx";
import * as $14 from "./routes/dcat.tsx";
import * as $15 from "./routes/document/[slug].tsx";
import * as $16 from "./routes/documents.tsx";
import * as $17 from "./routes/doi.tsx";
import * as $18 from "./routes/fakturering.tsx";
import * as $19 from "./routes/home.tsx";
import * as $20 from "./routes/index.tsx";
import * as $21 from "./routes/legacy.tsx";
import * as $22 from "./routes/legacy_pages_redirect.tsx";
import * as $23 from "./routes/ms-louise.tsx";
import * as $24 from "./routes/mynewsdesk-articles/[slug].tsx";
import * as $25 from "./routes/nav.tsx";
import * as $26 from "./routes/news.tsx";
import * as $27 from "./routes/null.tsx";
import * as $28 from "./routes/policies.tsx";
import * as $29 from "./routes/pref.tsx";
import * as $30 from "./routes/project.tsx";
import * as $31 from "./routes/projects.tsx";
import * as $32 from "./routes/pubs.tsx";
import * as $33 from "./routes/research.tsx";
import * as $34 from "./routes/research_topics.tsx";
import * as $35 from "./routes/search.tsx";
import * as $36 from "./routes/service_topics.tsx";
import * as $37 from "./routes/services.tsx";
import * as $38 from "./routes/sitemap.txt.ts";
import * as $39 from "./routes/topics.tsx";
import * as $40 from "./routes/usr.tsx";
import * as $$0 from "./islands/HScrollWithDynamicImage.tsx";
import * as $$1 from "./islands/button_open_dialog.tsx";
import * as $$2 from "./islands/doi_search.tsx";
import * as $$3 from "./islands/lang_switcher.tsx";
import * as $$4 from "./islands/text.tsx";
import * as $$5 from "./islands/theme_switcher.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/_middleware.ts": $3,
    "./routes/about.tsx": $4,
    "./routes/accreditation.tsx": $5,
    "./routes/akvaplanist.tsx": $6,
    "./routes/api/mynewsdesk/index.ts": $7,
    "./routes/api/mynewsdesk/type/[...path].ts": $8,
    "./routes/api/mynewsdesk/year/[...path].ts": $9,
    "./routes/api/projects.ts": $10,
    "./routes/api/slug/[type].ts": $11,
    "./routes/article/[slug].tsx": $12,
    "./routes/careers.tsx": $13,
    "./routes/dcat.tsx": $14,
    "./routes/document/[slug].tsx": $15,
    "./routes/documents.tsx": $16,
    "./routes/doi.tsx": $17,
    "./routes/fakturering.tsx": $18,
    "./routes/home.tsx": $19,
    "./routes/index.tsx": $20,
    "./routes/legacy.tsx": $21,
    "./routes/legacy_pages_redirect.tsx": $22,
    "./routes/ms-louise.tsx": $23,
    "./routes/mynewsdesk-articles/[slug].tsx": $24,
    "./routes/nav.tsx": $25,
    "./routes/news.tsx": $26,
    "./routes/null.tsx": $27,
    "./routes/policies.tsx": $28,
    "./routes/pref.tsx": $29,
    "./routes/project.tsx": $30,
    "./routes/projects.tsx": $31,
    "./routes/pubs.tsx": $32,
    "./routes/research.tsx": $33,
    "./routes/research_topics.tsx": $34,
    "./routes/search.tsx": $35,
    "./routes/service_topics.tsx": $36,
    "./routes/services.tsx": $37,
    "./routes/sitemap.txt.ts": $38,
    "./routes/topics.tsx": $39,
    "./routes/usr.tsx": $40,
  },
  islands: {
    "./islands/HScrollWithDynamicImage.tsx": $$0,
    "./islands/button_open_dialog.tsx": $$1,
    "./islands/doi_search.tsx": $$2,
    "./islands/lang_switcher.tsx": $$3,
    "./islands/text.tsx": $$4,
    "./islands/theme_switcher.tsx": $$5,
  },
  baseUrl: import.meta.url,
};

export default manifest;
